# Generated by Django 6.0.6 on 2026-07-11 17:46

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_ad_unit_id', models.CharField(blank=True, max_length=100, verbose_name='معرّف إعلان البانر (Banner)')),
                ('interstitial_ad_unit_id', models.CharField(blank=True, max_length=100, verbose_name='معرّف الإعلان البيني (Interstitial)')),
                ('banner_enabled', models.BooleanField(default=True, verbose_name='تفعيل إعلانات البانر')),
                ('interstitial_enabled', models.BooleanField(default=True, verbose_name='تفعيل الإعلانات البينية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الإعلانات',
                'verbose_name_plural': 'إعدادات الإعلانات (AdMob)',
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('device', models.CharField(blank=True, help_text='مثال: Android 14 - Samsung SM-G991B، يرسله التطبيق تلقائياً', max_length=150, verbose_name='الجهاز')),
                ('screen', models.CharField(blank=True, help_text='مثال: home, channel_open, news_detail', max_length=100, verbose_name='الشاشة/الحدث')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الإحصائيات (الزوار)',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القناة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='channels/logos/', verbose_name='شعار القناة')),
                ('stream_url', models.URLField(max_length=500, verbose_name='رابط البث المباشر')),
                ('category', models.CharField(choices=[('sports', 'رياضة'), ('news', 'أخبار'), ('general', 'عام')], default='sports', max_length=50, verbose_name='الفئة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'قناة',
                'verbose_name_plural': 'القنوات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(help_text='يُرسله تطبيق Flutter تلقائياً عند أول تشغيل', max_length=255, unique=True, verbose_name='رمز الجهاز (FCM Token)')),
                ('device_platform', models.CharField(choices=[('android', 'أندرويد'), ('ios', 'آيفون')], default='android', max_length=20, verbose_name='نظام الجهاز')),
                ('is_active', models.BooleanField(default=True, help_text='يُعطّل تلقائياً إذا رفض الرمز عند محاولة الإرسال (جهاز أُلغي تثبيت التطبيق منه)', verbose_name='نشِط؟')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
            ],
            options={
                'verbose_name': 'مشترك إشعارات',
                'verbose_name_plural': 'مشتركو الإشعارات (FCM)',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط انستغرام')),
                ('telegram_url', models.URLField(blank=True, verbose_name='رابط تيليجرام')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني للتواصل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'الإعدادات العامة',
                'verbose_name_plural': 'الإعدادات العامة (تواصل اجتماعي)',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('privacy_policy', 'سياسة الخصوصية'), ('about_us', 'من نحن')], max_length=30, unique=True, verbose_name='الصفحة')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان المعروض')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='المحتوى')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'صفحة ثابتة',
                'verbose_name_plural': 'الصفحات الثابتة',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفريق')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='شعار الفريق')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'فريق',
                'verbose_name_plural': 'الفرق',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(blank=True, max_length=150, verbose_name='البطولة/الدوري')),
                ('match_datetime', models.DateTimeField(verbose_name='موعد المباراة')),
                ('status', models.CharField(choices=[('upcoming', 'لم تبدأ بعد'), ('live', 'مباشر الآن'), ('finished', 'انتهت')], default='upcoming', max_length=10, verbose_name='حالة المباراة')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='أهداف الفريق المضيف')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='أهداف الفريق الضيف')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.channel', verbose_name='قناة البث')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team', verbose_name='الفريق الضيف')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team', verbose_name='الفريق المضيف')),
            ],
            options={
                'verbose_name': 'مباراة',
                'verbose_name_plural': 'المباريات',
                'ordering': ['match_datetime'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='صورة الخبر')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور؟')),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='core.match', verbose_name='مرتبط بمباراة')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم اللاعب')),
                ('shirt_number', models.PositiveIntegerField(default=0, verbose_name='رقم القميص')),
                ('position', models.CharField(choices=[('GK', 'حارس مرمى'), ('DF', 'مدافع'), ('MF', 'وسط'), ('FW', 'مهاجم')], default='MF', max_length=20, verbose_name='المركز')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team', verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'لاعب',
                'verbose_name_plural': 'اللاعبون',
                'ordering': ['team', 'shirt_number'],
            },
        ),
        migrations.CreateModel(
            name='LineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField(default=True, verbose_name='أساسي؟')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='core.match', verbose_name='المباراة')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'عنصر تشكيلة',
                'verbose_name_plural': 'التشكيلات',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
