JAZZMIN_SETTINGS = {
    'site_title': 'Dilmi TV',
    'site_header': 'Dilmi TV',
    'site_brand': 'Dilmi TV',
    'site_logo': 'images/site_logo.png',
    'login_logo': 'images/site_logo.png',
    'login_logo_dark': 'images/site_logo.png',
    'site_icon': 'images/site_logo.png',
    'welcome_sign': 'مرحباً بك في لوحة إدارة Dilmi TV',
    'copyright': 'Dilmi TV',
    'search_model': ['core.Channel', 'core.Team', 'core.Match', 'core.News'],
    'topmenu_links': [{'name': 'عرض الموقع', 'url': '/', 'new_window': True}, {'model': 'auth.User'}],
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.Group': 'fas fa-users',
        'auth.User': 'fas fa-user',
        'core.Channel': 'fas fa-tv',
        'core.Team': 'fas fa-shield-alt',
        'core.Player': 'fas fa-running',
        'core.Match': 'fas fa-futbol',
        'core.LineupEntry': 'fas fa-list-ol',
        'core.News': 'fas fa-newspaper',
        'core.AdSettings': 'fas fa-ad',
        'core.SiteSettings': 'fas fa-share-alt',
        'core.StaticPage': 'fas fa-file-alt',
        'core.Analytics': 'fas fa-chart-line',
        'core.NotificationSubscriber': 'fas fa-bell',
    },
    'order_with_respect_to': [
        'core.Channel', 'core.Team', 'core.Player', 'core.Match',
        'core.LineupEntry', 'core.News',
        'core.AdSettings', 'core.SiteSettings', 'core.StaticPage',
        'core.Analytics', 'core.NotificationSubscriber',
        'auth',
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'changeform_format': 'horizontal_tabs',
    # --- التعديلات الضرورية هنا لإنهاء الخطأ ---
    'related_modal_active': False, 
    'show_ui_builder': False,
    # ------------------------------------------
    'custom_css': 'admin/css/jazzmin_custom.css',
}
