# Generated by Django 5.0.6 on 2026-07-14 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القناة")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="channels/logos/",
                        verbose_name="شعار القناة",
                    ),
                ),
                (
                    "stream_url",
                    models.URLField(
                        max_length=500, verbose_name="رابط البث (M3U8/HLS)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "رياضة"),
                            ("news", "أخبار"),
                            ("general", "عام"),
                        ],
                        default="sports",
                        max_length=20,
                        verbose_name="التصنيف",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشِطة؟")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب الظهور"),
                ),
            ],
            options={
                "verbose_name": "قناة",
                "verbose_name_plural": "القنوات",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "category"],
                        name="core_channe_is_acti_d5513b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "home_team",
                    models.CharField(max_length=100, verbose_name="الفريق المضيف"),
                ),
                (
                    "away_team",
                    models.CharField(max_length=100, verbose_name="الفريق الضيف"),
                ),
                (
                    "home_team_logo_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="شعار الفريق المضيف (رابط خارجي)",
                    ),
                ),
                (
                    "away_team_logo_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="شعار الفريق الضيف (رابط خارجي)",
                    ),
                ),
                (
                    "competition",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="البطولة/الدوري"
                    ),
                ),
                (
                    "match_datetime",
                    models.DateTimeField(db_index=True, verbose_name="موعد المباراة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "لم تبدأ بعد"),
                            ("live", "مباشر الآن"),
                            ("finished", "انتهت"),
                        ],
                        default="upcoming",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "home_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="أهداف المضيف"
                    ),
                ),
                (
                    "away_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="أهداف الضيف"
                    ),
                ),
                (
                    "elapsed_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="الدقيقة الحالية"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="المعرّف الخارجي",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="core.channel",
                        verbose_name="قناة البث",
                    ),
                ),
            ],
            options={
                "verbose_name": "مباراة",
                "verbose_name_plural": "المباريات",
                "ordering": ["match_datetime"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="العنوان")),
                ("content", models.TextField(verbose_name="المحتوى")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/images/",
                        verbose_name="صورة الخبر (رفع يدوي)",
                    ),
                ),
                (
                    "external_image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="رابط صورة خارجي",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="مفتاح فريد لمنع تكرار نفس الخبر عند إعادة تشغيل sync_data",
                        max_length=500,
                        null=True,
                        unique=True,
                        verbose_name="رابط المصدر",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="منشور؟"
                    ),
                ),
                (
                    "related_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_items",
                        to="core.match",
                        verbose_name="مرتبط بمباراة",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "الأخبار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status"], name="core_match_status_b71399_idx"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="core_news_is_publ_ce555a_idx",
            ),
        ),
    ]
