# Generated by Django 5.2.16 on 2026-07-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_migrate_stream_urls_to_streamsource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="stream_url",
        ),
    ]
