# Generated by Django 5.2.16 on 2026-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_news_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="المعرّف"
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=100, verbose_name="الاسم المعروض"),
                ),
                (
                    "is_healthy",
                    models.BooleanField(default=True, verbose_name="متصل بنجاح؟"),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر محاولة"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر نجاح"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="آخر رسالة خطأ"),
                ),
            ],
            options={
                "verbose_name": "حالة تكامل خارجي",
                "verbose_name_plural": "حالة التكاملات الخارجية",
            },
        ),
    ]
