# Generated by Django 5.2.16 on 2026-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_integration_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="stream_url",
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="رابط البث المباشر (خاص بالمباراة)",
            ),
        ),
    ]
