# Generated by Django 5.2.16 on 2026-07-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_match_stream_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="admob_app_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="AdMob — معرّف التطبيق (App ID)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="admob_banner_ad_unit_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="AdMob — معرّف إعلان البانر (Banner)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="admob_enabled",
            field=models.BooleanField(default=False, verbose_name="تفعيل AdMob"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="admob_interstitial_ad_unit_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="AdMob — معرّف الإعلان البيني (Interstitial)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="admob_rewarded_ad_unit_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="AdMob — معرّف الإعلان المكافأ (Rewarded)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ads_enabled",
            field=models.BooleanField(
                default=False,
                verbose_name="تفعيل الإعلانات في التطبيق (المفتاح الرئيسي)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_ads_enabled",
            field=models.BooleanField(
                default=False, verbose_name="تفعيل Meta / Facebook Audience Network"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_ads_interstitial_placement_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Facebook Audience Network — معرّف موضع الإعلان البيني (Interstitial)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_ads_placement_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Facebook Audience Network — معرّف موضع البانر (Banner)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_ads_rewarded_placement_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Facebook Audience Network — معرّف موضع الإعلان المكافأ (Rewarded)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="other_ad_banner_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="الشبكة الأخرى — معرّف إعلان البانر (Banner)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="other_ad_interstitial_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="الشبكة الأخرى — معرّف الإعلان البيني (Interstitial)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="other_ad_network_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="اسم الشبكة الإعلانية الأخرى"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="other_ad_rewarded_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="الشبكة الأخرى — معرّف الإعلان المكافأ (Rewarded)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="other_ads_enabled",
            field=models.BooleanField(
                default=False, verbose_name="تفعيل شبكة إعلانية أخرى"
            ),
        ),
    ]
