# Generated by Django 5.2.16 on 2026-07-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_sitesettings_admob_app_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="app_ads_txt",
            field=models.TextField(
                blank=True,
                help_text="سطر واحد لكل شبكة إعلانية، بالصيغة التي تعطيها لك الشبكة نفسها (مثال من AdMob: google.com, pub-XXXXXXXXXXXXXXXX, DIRECT, f08c47fec0942fa0)",
                verbose_name="محتوى ملف app-ads.txt",
            ),
        ),
    ]
