# Generated by Django 5.0.6 on 2026-07-14 01:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewerSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="وقت اللقطة"
                    ),
                ),
                (
                    "live_viewers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدين"
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة مشاهدين",
                "verbose_name_plural": "لقطات المشاهدين",
                "ordering": ["-taken_at"],
            },
        ),
        migrations.CreateModel(
            name="ViewerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="معرّف الجهاز"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("phone", "هاتف"),
                            ("tablet", "جهاز لوحي"),
                            ("tv", "شاشة ذكية"),
                            ("web", "متصفح"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="المنصة",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="أول ظهور"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="آخر نبضة"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewer_sessions",
                        to="core.channel",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewer_sessions",
                        to="core.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة مشاهدة",
                "verbose_name_plural": "جلسات المشاهدة",
                "indexes": [
                    models.Index(
                        fields=["last_seen"], name="analytics_v_last_se_a390bc_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="viewersession",
            constraint=models.UniqueConstraint(
                fields=("device_id", "channel", "match"), name="unique_device_target"
            ),
        ),
    ]
