# Generated by Django 5.2.16 on 2026-07-15 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000, verbose_name="الرابط")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="مثال: HD، احتياطي 1... (اختياري، لتمييز الرابط فقط)",
                        max_length=100,
                        verbose_name="تسمية",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = يُجرَّب أولاً. الأرقام الأصغر لها أولوية أعلى.",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="يُعطَّل تلقائياً بعد عدة فحوصات فاشلة متتالية، أو يدوياً من هنا.",
                        verbose_name="نشِط؟",
                    ),
                ),
                (
                    "is_healthy",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="سليم في آخر فحص؟"
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="فحوصات فاشلة متتالية"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="آخر فحص"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="core.channel",
                        verbose_name="القناة",
                    ),
                ),
            ],
            options={
                "verbose_name": "رابط بث",
                "verbose_name_plural": "روابط البث",
                "ordering": ["priority", "-is_healthy", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "is_active", "priority"],
                        name="streaming_s_channel_6a6158_idx",
                    )
                ],
            },
        ),
    ]
